apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-playground
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-playground
  template:
    metadata:
      labels:
        app: iot-playground
    spec:
      containers:
        - name: playground
          image: hnaciri/iot:v1
          ports:
            - containerPort: 1337
